model: openai/gpt-oss-20b

modelParameters:
  maxModelLen: 8192

inference:
  serviceName: gpt-oss-20b-vllm
  serviceNamespace: default
  accelerator: gpu
  framework: vllm

  modelServer:
    env:
      VLLM_ATTENTION_BACKEND: TRITON_ATTN_VLLM_V1
    image:
      repository: public.ecr.aws/deep-learning-containers/vllm
      tag: 0.11.0-gpu-py312
    deployment:
      instanceType: g6e.2xlarge
